//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BankApp.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserMoney
    {
        public int UserMoneyId { get; set; }
        public Nullable<int> CurrencyId { get; set; }
        public double Value { get; set; }
        public Nullable<int> PersonId { get; set; }
    
        public virtual Currency Currency { get; set; }
        public virtual Person Person { get; set; }
    }
}
